const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function api(u,o={}){const r=await fetch(u,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Une erreur est survenue');return d}
const loginView=$('#loginView'),appView=$('#appView');function showLogin(){loginView.classList.remove('hidden');appView.classList.add('hidden');$('#logout').classList.add('hidden')}function showApp(){loginView.classList.add('hidden');appView.classList.remove('hidden');$('#logout').classList.remove('hidden');loadDashboard()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});showApp()}catch(x){$('#loginError').textContent=x.message}};$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});showLogin()};
function openView(n){$$('.admin-view').forEach(x=>x.classList.remove('active'));$('#'+n+'View').classList.add('active');$$('.side-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===n));if(n==='dashboard')loadDashboard();if(n==='formations')renderFormations();if(n==='categories')renderCategories();if(n==='users')renderUsers()}$$('.side-nav button').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>openView(b.dataset.go));$('#newFromDash').onclick=()=>{openView('formations');setTimeout(showForm,50)};$('#newFormation').onclick=showForm;$('#cancel').onclick=hideForm;
async function loadDashboard(){try{const d=await api('/api/videos');$('#sVideos').textContent=d.total;$('#sCats').textContent=d.categories.length;$('#sPlayable').textContent=d.videos.filter(v=>v.url).length;$('#recent').innerHTML=d.videos.slice(0,5).map(v=>`<div class="recent-item"><div class="recent-thumb">▶</div><div class="recent-info"><b>${esc(v.title)}</b><small>${esc(v.category||'Formation')} ${v.duration?'• '+esc(v.duration):''}</small></div><a class="recent-action" href="/video.html?id=${encodeURIComponent(v.id)}" target="_blank">Voir</a></div>`).join('')||'<p class="muted" style="font-size:12px">Aucune formation pour le moment.</p>'}catch(e){}}
function showForm(){document.querySelector('#form').scrollIntoView({behavior:'smooth'});$('#form').classList.remove('hidden')}function hideForm(){$('#form').reset();$('#editId').value='';$('#formTitle').textContent='Ajouter une formation';$('#submitBtn').textContent='Ajouter la formation';$('#cancel').classList.add('hidden');$('#formError').textContent=''}
async function renderFormations(){try{const d=await api('/api/videos');$('#formationTotal').textContent=`${d.total} formation(s)`;$('#list').innerHTML=d.videos.map(v=>`<div class="item"><div><b>${esc(v.title)}</b><div class="muted">${esc(v.category||'Formation')} ${v.duration?'• '+esc(v.duration):''}</div><small>${esc(v.description||'')}</small></div><div class="item-actions"><a class="ghost" href="/video.html?id=${encodeURIComponent(v.id)}" target="_blank">Voir</a><button class="ghost edit" data-id="${v.id}">Modifier</button><button class="danger del" data-id="${v.id}">Supprimer</button></div></div>`).join('')||'<p class="muted">Aucune formation.</p>';$$('.del').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cette formation ?')){await api('/api/videos/'+b.dataset.id,{method:'DELETE'});renderFormations();loadDashboard()}});$$('.edit').forEach(b=>b.onclick=async()=>{const d=await api('/api/videos/'+b.dataset.id),v=d.video;$('#editId').value=v.id;$('#title').value=v.title;$('#category').value=v.category;$('#description').value=v.description;$('#url').value=v.url;$('#duration').value=v.duration||'';$('#formTitle').textContent='Modifier la formation';$('#submitBtn').textContent='Enregistrer les modifications';$('#cancel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})})}catch(e){$('#list').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function renderCategories(){try{const d=await api('/api/videos');$('#categoryList').innerHTML=d.categories.map(c=>`<div class="quick-item"><b>▦ ${esc(c)}</b><span>${d.videos.filter(v=>v.category===c).length} formation(s)</span></div>`).join('')||'<p class="muted">Aucune catégorie.</p>'}catch(e){}}
$('#form').onsubmit=async e=>{e.preventDefault();$('#formError').textContent='';const id=$('#editId').value,p={title:$('#title').value,category:$('#category').value,description:$('#description').value,url:$('#url').value,duration:$('#duration').value};try{await api(id?'/api/videos/'+id:'/api/videos',{method:id?'PUT':'POST',body:JSON.stringify(p)});hideForm();renderFormations();loadDashboard()}catch(x){$('#formError').textContent=x.message}};(async()=>{try{const d=await api('/api/me');d.authenticated?showApp():showLogin()}catch{showLogin()}})();
function showUserForm(){ $('#userForm').classList.remove('hidden'); $('#userForm').scrollIntoView({behavior:'smooth'}); }
function hideUserForm(){ $('#userForm').reset(); $('#userEditId').value=''; $('#userFormTitle').textContent='Ajouter un utilisateur'; $('#userSubmit').textContent='Créer le compte'; $('#userPassword').placeholder='6 caractères minimum'; $('#cancelUser').classList.add('hidden'); $('#userError').textContent=''; }
$('#newUser').onclick=()=>{hideUserForm();showUserForm()}; $('#cancelUser').onclick=hideUserForm;
async function renderUsers(){try{const d=await api('/api/users');$('#userTotal').textContent=`${d.total} compte(s)`;$('#userList').innerHTML=d.users.map(u=>`<div class="item"><div><b>${esc(u.name)}</b><div class="muted">${esc(u.username)} • ${esc(u.role)} • ${u.active?'Actif':'Désactivé'}</div></div><div class="item-actions"><button class="ghost user-edit" data-id="${u.id}">Modifier</button><button class="danger user-del" data-id="${u.id}">Supprimer</button></div></div>`).join('')||'<p class="muted">Aucun compte utilisateur.</p>';
$$('.user-del').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer ce compte ?')){await api('/api/users/'+b.dataset.id,{method:'DELETE'});renderUsers()}});
$$('.user-edit').forEach(b=>b.onclick=async()=>{const d=await api('/api/users');const u=d.users.find(x=>x.id===b.dataset.id);if(!u)return;$('#userEditId').value=u.id;$('#userName').value=u.name;$('#userUsername').value=u.username;$('#userRole').value=u.role;$('#userPassword').value='';$('#userPassword').placeholder='Laisser vide pour conserver';$('#userFormTitle').textContent='Modifier l’utilisateur';$('#userSubmit').textContent='Enregistrer';$('#cancelUser').classList.remove('hidden');showUserForm()})}catch(e){$('#userList').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
$('#userForm').onsubmit=async e=>{e.preventDefault();$('#userError').textContent='';const id=$('#userEditId').value,p={name:$('#userName').value,username:$('#userUsername').value,role:$('#userRole').value,password:$('#userPassword').value};if(id&&!p.password)delete p.password;try{await api(id?'/api/users/'+id:'/api/users',{method:id?'PUT':'POST',body:JSON.stringify(p)});hideUserForm();renderUsers()}catch(x){$('#userError').textContent=x.message}};
