const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const sqlite3=require('sqlite3').verbose();

const ROOT=__dirname, DATA_DIR=path.join(ROOT,'data'), DB_FILE=path.join(DATA_DIR,'edutrack.sqlite'), VIDEO_DIR=path.join(ROOT,'videos');
const PORT=Number(process.env.PORT||3000);
const ADMIN_USER=process.env.EDUTRACK_ADMIN_USER||'admin';
const ADMIN_PASSWORD=process.env.EDUTRACK_ADMIN_PASSWORD||'';
const sessions=new Map();
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
if(!fs.existsSync(VIDEO_DIR))fs.mkdirSync(VIDEO_DIR,{recursive:true});
const db=new sqlite3.Database(DB_FILE);
const run=(sql,p=[])=>new Promise((res,rej)=>db.run(sql,p,function(e){e?rej(e):res(this)}));
const all=(sql,p=[])=>new Promise((res,rej)=>db.all(sql,p,(e,r)=>e?rej(e):res(r)));
const get=(sql,p=[])=>new Promise((res,rej)=>db.get(sql,p,(e,r)=>e?rej(e):res(r)));
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `${salt}:${hash}`}
function verifyPassword(password,stored){try{const [salt,hash]=String(stored).split(':');const actual=crypto.scryptSync(String(password),salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(actual,'hex'),Buffer.from(hash,'hex'))}catch{return false}}
async function init(){
 await run(`CREATE TABLE IF NOT EXISTS videos(id TEXT PRIMARY KEY,title TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Formation',description TEXT DEFAULT '',url TEXT NOT NULL,duration TEXT DEFAULT '',createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL)`);
 await run(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,passwordHash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'Agent',active INTEGER NOT NULL DEFAULT 1,createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL)`);
 const count=await get('SELECT COUNT(*) AS n FROM videos');
 if(!count.n&&fs.existsSync(path.join(DATA_DIR,'db.json'))){try{const old=JSON.parse(fs.readFileSync(path.join(DATA_DIR,'db.json'),'utf8'));for(const v of old.videos||[])await run('INSERT OR IGNORE INTO videos VALUES (?,?,?,?,?,?,?,?)',[v.id||crypto.randomUUID(),v.title||'Formation',v.category||'Formation',v.description||'',v.url||'',v.duration||'',v.createdAt||new Date().toISOString(),v.updatedAt||new Date().toISOString()])}catch(e){console.error('Migration db.json:',e.message)}}
 const count2=await get('SELECT COUNT(*) AS n FROM videos');
 if(!count2.n){const files=fs.readdirSync(VIDEO_DIR).filter(f=>/\.(mp4|webm|ogg|mov)$/i.test(f));const now=new Date().toISOString();for(const file of files)await run('INSERT INTO videos VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),file.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').trim()||'Formation','Formation','Découvrez cette formation vidéo EduTrack.','/videos/'+encodeURIComponent(file),'',now,now])}
}
function safeVideo(v){return {id:v.id,title:v.title,category:v.category,description:v.description,url:v.url,duration:v.duration||'',createdAt:v.createdAt,updatedAt:v.updatedAt}}
function safeUser(u){return {id:u.id,name:u.name,username:u.username,role:u.role,active:!!u.active,createdAt:u.createdAt,updatedAt:u.updatedAt}}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(body)}
function text(res,status,body,type='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':type});res.end(body)}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function currentUser(req){const t=cookies(req).edutrack_session;return t&&sessions.get(t)||null}
function isAuthed(req){return !!currentUser(req)}
function isAdmin(req){const u=currentUser(req);return !!u&&u.role==='Administrateur'}
function readBody(req,max=2*1024*1024){return new Promise((resolve,reject)=>{let d='',s=0;req.on('data',c=>{s+=c.length;if(s>max){reject(new Error('Payload trop volumineux'));req.destroy()}else d+=c});req.on('end',()=>resolve(d));req.on('error',reject)})}
function serveStatic(req,res,pathname){let rel=pathname==='/'?'/index.html':pathname;const file=path.normalize(path.join(ROOT,rel));if(!file.startsWith(ROOT))return text(res,403,'Interdit');if(!fs.existsSync(file)||fs.statSync(file).isDirectory())return text(res,404,'Fichier introuvable');const ext=path.extname(file).toLowerCase();const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.mp4':'video/mp4','.webm':'video/webm','.ogg':'video/ogg','.mov':'video/quicktime'};if(/\.(mp4|webm|ogg|mov)$/i.test(ext)){const stat=fs.statSync(file),size=stat.size,range=req.headers.range;if(range){const m=/bytes=(\d*)-(\d*)/.exec(range),start=m&&m[1]?Number(m[1]):0,end=m&&m[2]?Number(m[2]):size-1;if(start>=size||end>=size)return res.writeHead(416,{'Content-Range':`bytes */${size}`}).end();res.writeHead(206,{'Content-Type':types[ext],'Content-Length':end-start+1,'Content-Range':`bytes ${start}-${end}/${size}`,'Accept-Ranges':'bytes'});return fs.createReadStream(file,{start,end}).pipe(res)}res.writeHead(200,{'Content-Type':types[ext],'Content-Length':size,'Accept-Ranges':'bytes'});return fs.createReadStream(file).pipe(res)}res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(file).pipe(res)}
async function api(req,res,u){
 if(req.method==='POST'&&u.pathname==='/api/login'){try{const b=JSON.parse(await readBody(req));let user=null;if(b.username===ADMIN_USER&&b.password===ADMIN_PASSWORD)user={id:'admin',name:'Administrateur',username:ADMIN_USER,role:'Administrateur',active:true};else{const found=await get('SELECT * FROM users WHERE lower(username)=lower(?)',[String(b.username||'').trim()]);if(found&&found.active&&verifyPassword(b.password,found.passwordHash))user=safeUser(found)}if(!user)return json(res,401,{error:'Identifiants incorrects'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{id:user.id,name:user.name,username:user.username,role:user.role,createdAt:Date.now()});res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':`edutrack_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`});return res.end(JSON.stringify({ok:true,user}))}catch{return json(res,400,{error:'Requête invalide'})}}
 if(req.method==='POST'&&u.pathname==='/api/logout'){const c=cookies(req);if(c.edutrack_session)sessions.delete(c.edutrack_session);res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':'edutrack_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});return res.end('{"ok":true}')}
 if(u.pathname==='/api/me'){const user=currentUser(req);return json(res,200,{authenticated:!!user,user:user||null,username:user?.username||null,role:user?.role||null})}
 if(req.method==='GET'&&u.pathname==='/api/videos'){const q=(u.searchParams.get('q')||'').toLowerCase(),cat=u.searchParams.get('category')||'';let sql='SELECT * FROM videos WHERE 1=1',p=[];if(cat){sql+=' AND category=?';p.push(cat)}if(q){sql+=' AND lower(title||\' \'||description||\' \'||category) LIKE ?';p.push('%'+q+'%')}sql+=' ORDER BY createdAt DESC';const videos=await all(sql,p),total=await get('SELECT COUNT(*) AS n FROM videos'),cats=await all('SELECT DISTINCT category FROM videos WHERE category<>\'\' ORDER BY category');return json(res,200,{videos:videos.map(safeVideo),total:total.n,categories:cats.map(x=>x.category)})}
 if(req.method==='GET'&&u.pathname.startsWith('/api/videos/')){const v=await get('SELECT * FROM videos WHERE id=?',[u.pathname.split('/').pop()]);return v?json(res,200,{video:safeVideo(v)}):json(res,404,{error:'Vidéo introuvable'})}
 if(!isAuthed(req))return json(res,401,{error:'Authentification requise'});
 if(req.method==='GET'&&u.pathname==='/api/users'){if(!isAdmin(req))return json(res,403,{error:'Accès réservé à l’administrateur'});const users=await all('SELECT * FROM users ORDER BY createdAt DESC');return json(res,200,{users:users.map(safeUser),total:users.length})}
 if(req.method==='POST'&&u.pathname==='/api/users'){if(!isAdmin(req))return json(res,403,{error:'Accès réservé à l’administrateur'});try{const b=JSON.parse(await readBody(req));const name=String(b.name||'').trim(),username=String(b.username||'').trim(),password=String(b.password||''),role=['Agent','Responsable'].includes(b.role)?b.role:'Agent';if(!name||!username||password.length<6)return json(res,400,{error:'Nom, identifiant et mot de passe (6 caractères minimum) sont obligatoires'});const exists=await get('SELECT id FROM users WHERE lower(username)=lower(?)',[username]);if(exists)return json(res,409,{error:'Cet identifiant existe déjà'});const now=new Date().toISOString(),v={id:crypto.randomUUID(),name,username,passwordHash:hashPassword(password),role,active:1,createdAt:now,updatedAt:now};await run('INSERT INTO users (id,name,username,passwordHash,role,active,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)',[v.id,v.name,v.username,v.passwordHash,v.role,v.active,v.createdAt,v.updatedAt]);return json(res,201,{user:safeUser(v)})}catch(e){return json(res,400,{error:e.message})}}
 if(req.method==='PUT'&&u.pathname.startsWith('/api/users/')){if(!isAdmin(req))return json(res,403,{error:'Accès réservé à l’administrateur'});const id=u.pathname.split('/').pop(),u0=await get('SELECT * FROM users WHERE id=?',[id]);if(!u0)return json(res,404,{error:'Utilisateur introuvable'});try{const b=JSON.parse(await readBody(req));const name=b.name!==undefined?String(b.name).trim():u0.name,username=b.username!==undefined?String(b.username).trim():u0.username,role=['Agent','Responsable'].includes(b.role)?b.role:u0.role,active=b.active===undefined?!!u0.active:!!b.active;if(!name||!username)return json(res,400,{error:'Nom et identifiant obligatoires'});const other=await get('SELECT id FROM users WHERE lower(username)=lower(?) AND id<>?',[username,id]);if(other)return json(res,409,{error:'Cet identifiant existe déjà'});let sql='UPDATE users SET name=?,username=?,role=?,active=?,updatedAt=?',params=[name,username,role,active?1:0,new Date().toISOString()];if(b.password){if(String(b.password).length<6)return json(res,400,{error:'Le mot de passe doit contenir au moins 6 caractères'});sql+=',passwordHash=?';params.push(hashPassword(b.password))}sql+=' WHERE id=?';params.push(id);await run(sql,params);const fresh=await get('SELECT * FROM users WHERE id=?',[id]);return json(res,200,{user:safeUser(fresh)})}catch(e){return json(res,400,{error:e.message})}}
 if(req.method==='DELETE'&&u.pathname.startsWith('/api/users/')){if(!isAdmin(req))return json(res,403,{error:'Accès réservé à l’administrateur'});const id=u.pathname.split('/').pop(),r=await run('DELETE FROM users WHERE id=?',[id]);return r.changes?json(res,200,{ok:true}):json(res,404,{error:'Utilisateur introuvable'})}
 if(req.method==='POST'&&u.pathname==='/api/videos'){try{const b=JSON.parse(await readBody(req));if(!b.title||!b.url)return json(res,400,{error:'Titre et URL vidéo obligatoires'});const now=new Date().toISOString(),v={id:crypto.randomUUID(),title:String(b.title).trim(),category:String(b.category||'Formation').trim(),description:String(b.description||'').trim(),url:String(b.url).trim(),duration:String(b.duration||'').trim(),createdAt:now,updatedAt:now};await run('INSERT INTO videos VALUES (?,?,?,?,?,?,?,?)',Object.values(v));return json(res,201,{video:safeVideo(v)})}catch(e){return json(res,400,{error:e.message})}}
 if(req.method==='PUT'&&u.pathname.startsWith('/api/videos/')){const id=u.pathname.split('/').pop(),v=await get('SELECT * FROM videos WHERE id=?',[id]);if(!v)return json(res,404,{error:'Vidéo introuvable'});try{const b=JSON.parse(await readBody(req));const n={title:b.title!==undefined?String(b.title).trim():v.title,category:b.category!==undefined?String(b.category).trim():v.category,description:b.description!==undefined?String(b.description).trim():v.description,url:b.url!==undefined?String(b.url).trim():v.url,duration:b.duration!==undefined?String(b.duration).trim():v.duration,updatedAt:new Date().toISOString()};await run('UPDATE videos SET title=?,category=?,description=?,url=?,duration=?,updatedAt=? WHERE id=?',[n.title,n.category,n.description,n.url,n.duration,n.updatedAt,id]);return json(res,200,{video:safeVideo({...v,...n,id})})}catch(e){return json(res,400,{error:e.message})}}
 if(req.method==='DELETE'&&u.pathname.startsWith('/api/videos/')){const id=u.pathname.split('/').pop(),r=await run('DELETE FROM videos WHERE id=?',[id]);return r.changes?json(res,200,{ok:true}):json(res,404,{error:'Vidéo introuvable'})}
 return json(res,404,{error:'Route inconnue'})
}
(async()=>{await init();const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(u.pathname.startsWith('/api/'))await api(req,res,u);else serveStatic(req,res,u.pathname)}catch(e){console.error(e);json(res,500,{error:'Erreur serveur'})}});
server.listen(PORT,'0.0.0.0', ()=>console.log(`EduTrack Formation disponible sur http://localhost:${PORT}`));})();

